#!/bin/sh

powermenu="  Shutdown			poweroff || sudo poweroff
  Reboot			reboot || sudo reboot
  Reload dwm		dwmc rquit
  Log out			dwmc quit"

favoritesmenu="  Terminal			$TERMINAL
  Web				$BROWSER
  Media			mpv
  Files			$FILEBROWSER
ﭮ  Discord			discord
  Spotify			if pidof spotify; then dwmc toggleview 7; else spotify; fi
  Mail				thunderbird"

case $1 in
    # 1) rofi -show drun -config ~/.config/rofi/apps.rasi -fullscreen ;;
    1) xdg-xmenu | xmenu -p 0x0 | sh ;;
    2) echo "$favoritesmenu" | xmenu -p 0x0| sh ;;
    3) echo "$powermenu" | xmenu -p 0x0| sh ;;
esac
