#!/bin/sh

identifier="$RANDOM"
i3-msg mark "$identifier" > /dev/null
i3-msg [con_mark="$identifier"] move scratchpad > /dev/null
$@
i3-msg [con_mark="$identifier"] scratchpad show > /dev/null
i3-msg floating toggle > /dev/null
i3-msg unmark "$identifier" > /dev/null

